# Generated by Django 5.2.4 on 2026-01-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeaveNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("VACATION", "Отпуск"), ("DAY_OFF", "Отгул")],
                        max_length=30,
                    ),
                ),
                ("employee", models.CharField(max_length=254)),
                ("supervisor_tag", models.CharField(max_length=254)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("cancellable_until", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
