# Generated by Django 5.2.4 on 2026-01-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leavenotification",
            unique_together={("employee", "start_date")},
        ),
    ]
