# Generated by Django 5.2.4 on 2026-02-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_events", "0002_alter_leavenotification_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LeaveNotification",
            new_name="Leave",
        ),
    ]
