# Generated by Django 5.2.4 on 2026-02-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave_events", "0003_rename_leavenotification_leave"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leave",
            name="cancellable_until",
        ),
    ]
