# Generated by Django 5.2.4 on 2026-02-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_events", "0004_remove_leave_cancellable_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Нужно согласовать"),
                    ("approved", "Согласовано"),
                    ("deleted", "Удалено"),
                ],
                default="111",
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
