# Generated by Django 5.2.4 on 2026-02-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_events", "0005_leave_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="telegram_login",
            field=models.CharField(default="@no_login", max_length=254),
            preserve_default=False,
        ),
    ]
