# Generated by Django 5.2.4 on 2026-04-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_events", "0006_leave_telegram_login"),
        ("message_sender", "0008_alter_scheduledmessage_handler"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupervisorNotificationChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat",
                    models.CharField(
                        choices=[
                            ("domain_check", "domain_check"),
                            ("kva_test", "kva_test"),
                            ("asana_farm_comments", "asana_farm_comments"),
                            ("p1sms_balance", "p1sms_balance"),
                            ("offer_reawake", "offer_reawake"),
                            ("onboarding", "onboarding"),
                            ("hr_vacation", "hr_vacation"),
                            ("luckstar_accounts", "luckstar_accounts"),
                            ("kva_chat_test", "kva_chat_test"),
                            ("HR__TECH_DEP", "HR__TECH_DEP"),
                            ("HR__DIZ_DEP", "HR__DIZ_DEP"),
                            ("HR__FARM_DEP", "HR__FARM_DEP"),
                            ("HR__BIZ_DEV", "HR__BIZ_DEV"),
                            ("HR__VGA_TEAM", "HR__VGA_TEAM"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message_sender.atlasuser",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
