# Generated by Django 5.2.4 on 2025-11-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment_notifier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsanaComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("task_id", models.IntegerField()),
                ("comment_id", models.IntegerField()),
                (
                    "has_mention",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "is_notified",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
