# Generated by Django 5.2.4 on 2025-11-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment_notifier", "0002_asanacomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="asanacomment",
            name="task_url",
            field=models.URLField(blank=True),
        ),
    ]
