# Generated by Django 5.2.4 on 2025-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment_notifier", "0003_asanacomment_task_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asanacomment",
            name="comment_id",
            field=models.IntegerField(unique=True),
        ),
    ]
