# Generated by Django 5.2.4 on 2025-11-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment_notifier", "0004_alter_asanacomment_comment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="asanacomment",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
