# Generated by Django 5.2.4 on 2025-11-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment_notifier", "0005_asanacomment_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="asanacomment",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
