# Generated by Django 5.2.4 on 2025-11-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment_notifier", "0006_asanacomment_text"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AsanaProject",
            new_name="AsanaWebhookProject",
        ),
    ]
