# Generated by Django 5.2.4 on 2025-11-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment_notifier", "0007_rename_asanaproject_asanawebhookproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="asanawebhookproject",
            name="project_id",
            field=models.CharField(
                default="1210393628043121", max_length=50, unique=True
            ),
            preserve_default=False,
        ),
    ]
