# Generated by Django 5.2.4 on 2025-11-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment_notifier", "0008_asanawebhookproject_project_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="asanacomment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="comment_notifier.asanawebhookproject",
            ),
        ),
    ]
