# Generated by Django 5.2.4 on 2025-11-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment_notifier", "0009_asanacomment_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="asanawebhookproject",
            name="project_name",
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="asanawebhookproject",
            name="project_url",
            field=models.URLField(blank=True),
        ),
    ]
