# Generated by Django 5.2.4 on 2025-11-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comment_notifier", "0010_asanawebhookproject_project_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectIgnoredSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.CharField(max_length=30)),
                ("section_name", models.CharField(blank=True, max_length=254)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comment_notifier.asanawebhookproject",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "section_id")},
            },
        ),
    ]
