# Generated by Django 5.2.4 on 2025-11-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "comment_notifier",
            "0013_projectnotifysender_alter_asanacomment_send_result_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="asanacomment",
            name="comment_id",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="asanacomment",
            name="task_id",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="asanacomment",
            name="user_id",
            field=models.CharField(),
        ),
    ]
