# Generated by Django 5.2.4 on 2026-02-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0002_employee_delete_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="valentine_day/images/avatars",
            ),
        ),
    ]
