# Generated by Django 5.2.4 on 2026-02-06 18:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0003_alter_employee_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ValentineImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="valentine_day/images/for_valentines",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="valentine_day.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Valentine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("is_anonymously", models.BooleanField()),
                ("anonymous_signature", models.TextField(blank=True, max_length=50)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_valentines",
                        to="valentine_day.employee",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_valentines",
                        to="valentine_day.employee",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="valentine_day.valentineimage",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_anonymously", False),
                            ("anonymous_signature__gt", ""),
                            _connector="OR",
                        ),
                        name="anonymous_requires_signature",
                    )
                ],
                "unique_together": {("sender", "recipient")},
            },
        ),
    ]
