# Generated by Django 5.2.4 on 2026-02-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0004_employee_created_valentineimage_valentine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="image",
            new_name="avatar",
        ),
    ]
