# Generated by Django 5.2.4 on 2026-02-08 17:54

from django.db import migrations


def delete_employee(apps, schema_editor):
    Employee = apps.get_model("valentine_day", "Employee")
    Employee.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("valentine_day", "0005_rename_image_employee_avatar"),
    ]

    operations = [
        migrations.RunPython(delete_employee),
    ]
