# Generated by Django 5.2.4 on 2026-02-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0007_employee_user_alter_valentineimage_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="telegram_user_id",
            field=models.CharField(default=333333, max_length=30),
            preserve_default=False,
        ),
    ]
