# Generated by Django 5.2.4 on 2026-02-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0008_employee_telegram_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="valentineimage",
            name="owner",
        ),
    ]
