# Generated by Django 5.2.4 on 2026-02-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0010_valentineimage_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="telegram_user_id",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
