# Generated by Django 5.2.4 on 2026-02-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0011_alter_employee_telegram_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="valentine",
            name="is_read_by_recipient",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
