# Generated by Django 5.2.4 on 2026-02-10 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0012_valentine_is_read_by_recipient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="valentineimage",
            name="image",
            field=models.ImageField(
                default="1",
                max_length=255,
                upload_to="valentine_day/images/for_valentines",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="valentineimage",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
