# Generated by Django 5.2.4 on 2026-02-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0013_alter_valentineimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_open_app",
            field=models.BooleanField(default=False),
        ),
    ]
