# Generated by Django 5.2.4 on 2026-02-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0014_employee_is_open_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="sub_1",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="employee",
            name="telegram_login",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
