# Generated by Django 5.2.4 on 2026-02-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0015_employee_sub_1_employee_telegram_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="can_receive_valentine",
            field=models.BooleanField(default=True),
        ),
    ]
