# Generated by Django 5.2.4 on 2026-02-12 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0016_employee_can_receive_valentine"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_id", models.BigIntegerField(verbose_name="ID получателя")),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидание"),
                            ("success", "Успешно"),
                            ("error", "Ошибка"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_text",
                    models.TextField(blank=True, verbose_name="Текст ошибки"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Время создания"
                    ),
                ),
            ],
        ),
    ]
