# Generated by Django 5.2.4 on 2026-02-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0017_botmessagelog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="botmessagelog",
            old_name="recipient_id",
            new_name="chat_id",
        ),
    ]
