# Generated by Django 5.2.4 on 2026-02-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0018_rename_recipient_id_botmessagelog_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botmessagelog",
            name="chat_id",
            field=models.CharField(verbose_name="ID получателя"),
        ),
    ]
