# Generated by Django 5.2.4 on 2026-02-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("valentine_day", "0019_alter_botmessagelog_chat_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="valentine",
            unique_together=set(),
        ),
    ]
