# Generated by Django 5.2.4 on 2025-12-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsanaWebhookProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("project_id", models.CharField(max_length=50, unique=True)),
                ("project_name", models.CharField(blank=True, max_length=254)),
                ("project_url", models.URLField(blank=True)),
                ("secret", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AsanaWebhookRequestData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("headers", models.JSONField()),
                ("payload", models.JSONField()),
                ("is_target_event", models.BooleanField(default=None, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creative_quality.asanawebhookproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTargetSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.CharField(max_length=20, unique=True)),
                ("section_name", models.CharField(blank=True, max_length=254)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creative_quality.asanawebhookproject",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=20, unique=True)),
                ("task_name", models.CharField(blank=True, max_length=254)),
                ("is_complete", models.BooleanField(default=False)),
                ("assignee_id", models.CharField(blank=True, max_length=20)),
                ("bayer_code", models.CharField(blank=True, max_length=20)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creative_quality.asanawebhookproject",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Creative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_rated", models.BooleanField(default=False)),
                (
                    "hook",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "hold",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "crt",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("need_rated_at", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creative",
                        to="creative_quality.task",
                    ),
                ),
            ],
        ),
    ]
