# Generated by Django 5.2.4 on 2025-12-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative_quality", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projecttargetsection",
            name="project",
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("deleted", "Удален"),
                    ("created", "Создан"),
                    ("error_load_info", "Ошибка загрузки"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="AsanaWebhookRequestData",
        ),
        migrations.DeleteModel(
            name="AsanaWebhookProject",
        ),
        migrations.DeleteModel(
            name="ProjectTargetSection",
        ),
    ]
