# Generated by Django 5.2.4 on 2025-12-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creative_quality", "0002_remove_task_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreativeProjectSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_id", models.CharField(max_length=30)),
                ("section_name", models.CharField(blank=True, max_length=254)),
                ("project_name", models.CharField(blank=True, max_length=254)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
