# Generated by Django 5.2.4 on 2025-12-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creative_quality", "0003_creativeprojectsection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creative",
            name="is_rated",
        ),
        migrations.AddField(
            model_name="creative",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Ожидает оценки"),
                    ("rated", "Оценено"),
                    ("canceled", "Оценка отменена"),
                    ("expired", "Просрочено"),
                ],
                default="waiting",
                max_length=50,
            ),
        ),
    ]
