# Generated by Django 5.2.4 on 2025-12-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creative_quality", "0004_remove_creative_is_rated_creative_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_complete",
        ),
        migrations.AlterField(
            model_name="creative",
            name="need_rated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="creative",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Ожидает"),
                    ("need_review", "Нужна оценка"),
                    ("rated", "Оценено"),
                    ("canceled", "Оценка отменена"),
                    ("expired", "Просрочено"),
                ],
                default="waiting",
                max_length=50,
            ),
        ),
    ]
