# Generated by Django 5.2.4 on 2025-12-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "creative_quality",
            "0005_remove_task_is_complete_alter_creative_need_rated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="url",
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
