# Generated by Django 5.2.4 on 2025-12-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creative_quality", "0006_task_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="creative",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
