# Generated by Django 5.2.4 on 2025-12-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creative_quality", "0007_creative_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
