# Generated by Django 5.2.4 on 2025-12-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative_quality", "0008_task_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="creative",
            name="next_reminder_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creative",
            name="reminder_fail_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="creative",
            name="reminder_failure_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="creative",
            name="reminder_success_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="creative",
            name="crt",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creative",
            name="hold",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creative",
            name="hook",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creative",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Ожидает"),
                    ("need_review", "Нужна оценка"),
                    ("rated", "Оценено"),
                    ("reminder_limit_reached", "Лимит напоминаний достигнут"),
                    ("canceled", "Оценка отменена"),
                    ("expired", "Просрочено"),
                ],
                default="waiting",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignee_id",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Исполнитель"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="bayer_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="Код баера"),
        ),
    ]
