# Generated by Django 5.2.4 on 2025-12-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative_quality", "0009_creative_next_reminder_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="load_failure_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
