# Generated by Django 5.2.4 on 2025-12-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative_quality", "0010_task_load_failure_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="creative",
            name="gsheet_sent",
            field=models.BooleanField(default=False),
        ),
    ]
