# Generated by Django 5.2.4 on 2025-12-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creative_quality", "0011_creative_gsheet_sent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creative",
            old_name="crt",
            new_name="ctr",
        ),
    ]
