# Generated by Django 5.2.4 on 2025-12-16 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative_quality", "0012_rename_crt_creative_ctr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creative",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="creative",
            name="ctr",
        ),
        migrations.RemoveField(
            model_name="creative",
            name="hold",
        ),
        migrations.RemoveField(
            model_name="creative",
            name="hook",
        ),
        migrations.CreateModel(
            name="CreativeGeoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hook", models.PositiveIntegerField()),
                ("hold", models.PositiveIntegerField()),
                ("ctr", models.PositiveIntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "creative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_data",
                        to="creative_quality.creative",
                    ),
                ),
            ],
        ),
    ]
