# Generated by Django 5.2.4 on 2025-12-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        (
            "creative_quality",
            "0013_remove_creative_comment_remove_creative_ctr_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="creativegeodata",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.country",
            ),
            preserve_default=False,
        ),
    ]
