# Generated by Django 5.2.4 on 2025-12-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("creative_quality", "0014_creativegeodata_country"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="creativegeodata",
            unique_together={("creative", "country")},
        ),
    ]
