# Generated by Django 5.2.4 on 2025-12-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creative_quality", "0015_alter_creativegeodata_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creativegeodata",
            name="ctr",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="creativegeodata",
            name="hold",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="creativegeodata",
            name="hook",
            field=models.FloatField(),
        ),
    ]
