# Generated by Django 5.2.4 on 2025-12-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "creative_quality",
            "0016_alter_creativegeodata_ctr_alter_creativegeodata_hold_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="creativegeodata",
            name="status",
            field=models.CharField(
                choices=[("зашел", "Зашел"), ("незашел", "Не зашел")],
                default="зашел",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
