# Generated by Django 5.2.4 on 2026-01-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative_quality", "0017_creativegeodata_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="work_url",
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
