# Generated by Django 5.2.4 on 2026-01-23 08:54

import django.db.models.deletion
from django.db import migrations, models

def delete_tasks(apps, schema_editor):
    Model = apps.get_model("creative_quality", "Task")
    Model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("creative_quality", "0018_task_work_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreativeAdaptation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "creative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="creative_quality.creative",
                    ),
                ),
            ],
        ),
        migrations.RunPython(delete_tasks),
        migrations.AlterField(
            model_name="creativegeodata",
            name="creative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="geo_data",
                to="creative_quality.creativeadaptation",
            ),
        ),
    ]
