# Generated by Django 5.2.4 on 2026-01-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("creative_quality", "0019_creativeadaptation_alter_creativegeodata_creative"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creativegeodata",
            old_name="creative",
            new_name="creative_adaptation",
        ),
        migrations.AlterUniqueTogether(
            name="creativegeodata",
            unique_together={("creative_adaptation", "country")},
        ),
    ]
