# Generated by Django 5.2.4 on 2026-01-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "creative_quality",
            "0020_rename_creative_creativegeodata_creative_adaptation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="creativeadaptation",
            name="creative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adaptations",
                related_query_name="adaptation",
                to="creative_quality.creative",
            ),
        ),
    ]
