# Generated by Django 5.2.4 on 2026-02-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative_quality", "0021_alter_creativeadaptation_creative"),
    ]

    operations = [
        migrations.AddField(
            model_name="creativegeodata",
            name="cpm",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="creativegeodata",
            name="spend",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="creativegeodata",
            name="video_type",
            field=models.CharField(
                choices=[("post", "Пост"), ("ads", "Ads")], default="ads", max_length=30
            ),
            preserve_default=False,
        ),
    ]
