# Generated by Django 5.2.4 on 2026-02-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative_quality", "0022_creativegeodata_cpm_creativegeodata_spend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creativegeodata",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="creativegeodata",
            name="video_type",
            field=models.CharField(
                choices=[
                    ("post_w_button", "Пост с кнопкой"),
                    ("post_without_button", "Пост без кнопки"),
                    ("ads", "Ads"),
                ],
                max_length=30,
            ),
        ),
    ]
