# Generated by Django 5.2.4 on 2026-03-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creative_quality", "0023_alter_creativegeodata_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
