# Generated by Django 5.2.4 on 2026-03-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creative_quality", "0024_task_is_complete"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="is_completed",
            new_name="is_completed_in_asana",
        ),
    ]
