# Generated by Django 5.2.4 on 2025-11-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webhook_id", models.IntegerField(unique=True)),
                ("description", models.CharField(blank=True, max_length=254)),
            ],
        ),
    ]
