# Generated by Django 5.2.4 on 2025-11-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhook_pinger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="resource_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="webhook",
            name="resource_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="webhook",
            name="target",
            field=models.URLField(blank=True),
        ),
    ]
