# Generated by Django 5.2.4 on 2025-11-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhook_pinger", "0002_webhook_resource_name_webhook_resource_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="webhook_id",
            field=models.CharField(unique=True),
        ),
    ]
