# Generated by Django 5.2.4 on 2025-07-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsanaWebhookRequestData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("headers", models.JSONField()),
                ("payload", models.JSONField()),
                ("is_target_event", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CompletedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("event_data", models.JSONField()),
                ("task_id", models.CharField(max_length=100)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asana.asanawebhookrequestdata",
                    ),
                ),
            ],
        ),
    ]
