# Generated by Django 5.2.4 on 2025-11-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AtlasUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.PositiveIntegerField(unique=True)),
                ("atlas_profile_id", models.PositiveIntegerField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=254)),
                ("avatar_url", models.URLField(blank=True)),
            ],
        ),
    ]
