# Generated by Django 5.2.4 on 2025-07-23 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asanawebhookrequestdata",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="asana.asanaproject"
            ),
        ),
    ]
