# Generated by Django 5.2.4 on 2025-11-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asana", "0002_alter_atlasuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atlasuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
