# Generated by Django 5.2.4 on 2025-07-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0002_alter_asanawebhookrequestdata_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="asanaproject",
            name="table_url",
            field=models.CharField(
                default="add_task_tech", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
