# Generated by Django 5.2.4 on 2025-11-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asana", "0003_alter_atlasuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="atlasuser",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[("buyer", "Баер"), ("farmer", "Фармер")],
                max_length=32,
                verbose_name="Позиция",
            ),
        ),
    ]
