# Generated by Django 5.2.4 on 2025-07-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0003_asanaproject_table_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="completedtask",
            name="status_code",
        ),
        migrations.AddField(
            model_name="completedtask",
            name="error_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="completedtask",
            name="is_send_in_table",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
