# Generated by Django 5.2.4 on 2025-11-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0004_atlasuser_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atlasuser",
            old_name="atlas_profile_id",
            new_name="membership_id",
        ),
    ]
