# Generated by Django 5.2.4 on 2025-07-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0004_remove_completedtask_status_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedtask",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="asana.asanaproject"
            ),
        ),
    ]
