# Generated by Django 5.2.4 on 2025-11-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asana", "0005_rename_atlas_profile_id_atlasuser_membership_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="atlasuser",
            name="messenger_code",
            field=models.CharField(blank=True, choices=[("kva_tech", "KVA"), ("dav", "DAV")], max_length=32),
        ),
    ]
