# Generated by Django 5.2.4 on 2025-11-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0006_atlasuser_messenger_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atlasuser",
            name="messenger_code",
            field=models.CharField(
                blank=True,
                choices=[("kva_tech", "KVA"), ("dav", "DAV")],
                max_length=32,
                unique=True,
            ),
        ),
    ]
