# Generated by Django 5.2.4 on 2025-11-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0007_alter_atlasuser_messenger_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atlasuser",
            name="avatar_url",
            field=models.URLField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="atlasuser",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("buyer", "Баер"),
                    ("farmer", "Фармер"),
                    ("manager", "Менеджер"),
                ],
                max_length=32,
                verbose_name="Позиция",
            ),
        ),
    ]
