# Generated by Django 5.2.4 on 2025-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asana", "0008_alter_atlasuser_avatar_url_alter_atlasuser_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atlasuser",
            name="messenger_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("adm", "ADM"),
                    ("alisasalamahina", "ALISA_SALAMAHINA"),
                    ("vga", "VGA"),
                    ("mgp", "MGP"),
                    ("mse", "MSE"),
                    ("bya2", "BYA2"),
                    ("apa", "APA"),
                    ("paa", "PAA"),
                    ("dav", "DAV"),
                    ("kky", "KKY"),
                    ("mmi", "MMI"),
                    ("iae", "IAE"),
                    ("zva", "ZVA"),
                    ("mda", "MDA"),
                    ("testu", "TESTU"),
                    ("bsy", "BSY"),
                    ("dnl", "DNL"),
                    ("kva_tech", "KVA_TECH"),
                    ("kov", "KOV"),
                    ("pev", "PEV"),
                    ("raa", "RAA"),
                    ("bry", "BRY"),
                    ("fbapp", "FBAPP"),
                    ("svs", "SVS"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
    ]
