# Generated by Django 5.2.4 on 2025-11-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asana", "0010_alter_atlasuser_messenger_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atlasuser",
            name="membership_id",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="atlasuser",
            name="user_id",
            field=models.CharField(unique=True),
        ),
    ]
