# Generated by Django 5.2.4 on 2025-12-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asana", "0011_alter_atlasuser_membership_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsanaWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("resource_id", models.CharField(max_length=50)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("project", "Проект"), ("section", "Секция")],
                        max_length=50,
                    ),
                ),
                ("resource_name", models.CharField(blank=True, max_length=254)),
                ("secret", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WebhookHandler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="atlasuser",
            name="messenger_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ace_alc", "ACE_ALC"),
                    ("ace_ayc", "ACE_AYC"),
                    ("ace_bac", "ACE_BAC"),
                    ("ace_bvg", "ACE_BVG"),
                    ("ace_edg", "ACE_EDG"),
                    ("ace_fag", "ACE_FAG"),
                    ("ace_sgg", "ACE_SGG"),
                    ("adm", "ADM"),
                    ("alisasalamahina", "ALISA_SALAMAHINA"),
                    ("apa", "APA"),
                    ("bry", "BRY"),
                    ("bsy", "BSY"),
                    ("bya2", "BYA2"),
                    ("dav", "DAV"),
                    ("dnl", "DNL"),
                    ("fbapp", "FBAPP"),
                    ("iae", "IAE"),
                    ("kky", "KKY"),
                    ("kov", "KOV"),
                    ("kva_tech", "KVA_TECH"),
                    ("mda", "MDA"),
                    ("mgp", "MGP"),
                    ("mjj", "MJJ"),
                    ("mmi", "MMI"),
                    ("mmv", "MMV"),
                    ("mse", "MSE"),
                    ("paa", "PAA"),
                    ("pev", "PEV"),
                    ("raa", "RAA"),
                    ("sgm", "SGM"),
                    ("svs", "SVS"),
                    ("testu", "TESTU"),
                    ("vga", "VGA"),
                    ("zva", "ZVA"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AsanaWebhookRequestData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headers", models.JSONField()),
                ("payload", models.JSONField()),
                ("is_target_event", models.BooleanField(default=None, null=True)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asana.asanawebhook",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="asanawebhook",
            name="handlers",
            field=models.ManyToManyField(related_name="webhooks", to="asana.webhookhandler"),
        ),
    ]
