# Generated by Django 5.2.4 on 2025-12-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0012_asanawebhook_webhookhandler_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asanawebhookrequestdata",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("success", "Успешно"),
                    ("partial", "Частично"),
                    ("failed", "Ошибка"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="asanawebhook",
            name="handlers",
            field=models.ManyToManyField(
                blank=True, related_name="webhooks", to="asana.webhookhandler"
            ),
        ),
    ]
