# Generated by Django 5.2.4 on 2025-12-09 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("asana", "0013_asanawebhookrequestdata_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asanawebhookrequestdata",
            name="is_target_event",
        ),
    ]
