# Generated by Django 5.2.4 on 2025-12-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0014_remove_asanawebhookrequestdata_is_target_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asanawebhookrequestdata",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("success", "Успешно"),
                    ("partial", "Частично"),
                    ("failed", "Ошибка"),
                    ("no_handlers", "Нет слушателей"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="atlasuser",
            name="messenger_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ace_alc", "ACE_ALC"),
                    ("ace_ayc", "ACE_AYC"),
                    ("ace_bac", "ACE_BAC"),
                    ("ace_bvg", "ACE_BVG"),
                    ("ace_edg", "ACE_EDG"),
                    ("ace_fag", "ACE_FAG"),
                    ("ace_sgg", "ACE_SGG"),
                    ("adm", "ADM"),
                    ("alisasalamahina", "ALISA_SALAMAHINA"),
                    ("apa", "APA"),
                    ("bry", "BRY"),
                    ("bsy", "BSY"),
                    ("bya2", "BYA2"),
                    ("can", "CAN"),
                    ("dav", "DAV"),
                    ("dnl", "DNL"),
                    ("fbapp", "FBAPP"),
                    ("iae", "IAE"),
                    ("kav", "KAV"),
                    ("kky", "KKY"),
                    ("kov", "KOV"),
                    ("kva_tech", "KVA_TECH"),
                    ("mda", "MDA"),
                    ("mgp", "MGP"),
                    ("mjj", "MJJ"),
                    ("mmi", "MMI"),
                    ("mmv", "MMV"),
                    ("mse", "MSE"),
                    ("mya", "MYA"),
                    ("paa", "PAA"),
                    ("pev", "PEV"),
                    ("raa", "RAA"),
                    ("sgm", "SGM"),
                    ("svs", "SVS"),
                    ("svv", "SVV"),
                    ("testu", "TESTU"),
                    ("vga", "VGA"),
                    ("zva", "ZVA"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="atlasuser",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("buyer", "Баер"),
                    ("farmer", "Фармер"),
                    ("manager", "Менеджер"),
                    ("designer", "Дизайнер"),
                ],
                max_length=32,
                verbose_name="Позиция",
            ),
        ),
    ]
