# Generated by Django 5.2.4 on 2025-12-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0017_alter_atlasuser_messenger_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atlasuser",
            name="messenger_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ace_alc", "ACE_ALC"),
                    ("ace_ayc", "ACE_AYC"),
                    ("ace_bac", "ACE_BAC"),
                    ("ace_bvg", "ACE_BVG"),
                    ("ace_edg", "ACE_EDG"),
                    ("ace_fag", "ACE_FAG"),
                    ("ace_sgg", "ACE_SGG"),
                    ("adm", "ADM"),
                    ("avk", "AVK"),
                    ("alisasalamahina", "ALISA_SALAMAHINA"),
                    ("apa", "APA"),
                    ("bry", "BRY"),
                    ("bpa", "BPA"),
                    ("bsy", "BSY"),
                    ("bya2", "BYA2"),
                    ("can", "CAN"),
                    ("dav", "DAV"),
                    ("dnl", "DNL"),
                    ("fbapp", "FBAPP"),
                    ("iae", "IAE"),
                    ("kav", "KAV"),
                    ("kky", "KKY"),
                    ("kov", "KOV"),
                    ("kva_tech", "KVA_TECH"),
                    ("mda", "MDA"),
                    ("mgp", "MGP"),
                    ("mjj", "MJJ"),
                    ("mmi", "MMI"),
                    ("mmv", "MMV"),
                    ("mse", "MSE"),
                    ("mya", "MYA"),
                    ("omf", "OMF"),
                    ("omn", "OMN"),
                    ("paa", "PAA"),
                    ("pev", "PEV"),
                    ("raa", "RAA"),
                    ("sgm", "SGM"),
                    ("svs", "SVS"),
                    ("svv", "SVV"),
                    ("testu", "TESTU"),
                    ("vga", "VGA"),
                    ("vva", "VVA"),
                    ("zva", "ZVA"),
                ],
                default="",
                max_length=32,
            ),
            preserve_default=False,
        ),
    ]
