# Generated by Django 5.2.4 on 2026-01-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0018_alter_atlasuser_messenger_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atlasuser",
            name="messenger_code",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
