# Generated by Django 5.2.4 on 2026-01-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0019_alter_atlasuser_messenger_code"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AtlasUser",
            new_name="AtlasAsanaUser",
        ),
    ]
