# Generated by Django 5.2.4 on 2026-01-20 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0020_rename_atlasuser_atlasasanauser"),
        ("message_sender", "0002_alter_atlasuser_telegram"),
    ]

    operations = [
        migrations.AddField(
            model_name="atlasasanauser",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="message_sender.atlasuser",
            ),
        ),
    ]
