# Generated by Django 5.2.4 on 2026-03-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0021_atlasasanauser_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asanawebhook",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("project", "Проект"),
                    ("section", "Секция"),
                    ("task", "Задача"),
                ],
                max_length=50,
            ),
        ),
    ]
