# Generated by Django 5.2.4 on 2026-04-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0022_alter_asanawebhook_resource_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atlasasanauser",
            name="messenger_code",
        ),
    ]
