# Generated by Django 5.2.4 on 2026-04-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0023_remove_atlasasanauser_messenger_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="atlasasanauser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="asana/avatars/"),
        ),
    ]
