# Generated by Django 5.2.4 on 2026-04-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asana", "0024_atlasasanauser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="atlasasanauser",
            name="loaded_avatar_url",
            field=models.URLField(blank=True, max_length=254),
        ),
    ]
