# Generated by Django 5.2.4 on 2026-03-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offboarding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offboardingtask",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
