# Generated by Django 5.2.4 on 2026-03-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offboarding", "0002_offboardingtask_is_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="offboardingtask",
            name="notified_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offboardingtask",
            name="notified_created",
            field=models.BooleanField(default=False),
        ),
    ]
