# Generated by Django 5.2.4 on 2026-03-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offboarding", "0003_offboardingtask_notified_completed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offboardingtask",
            old_name="notify_at",
            new_name="notified_created_at",
        ),
    ]
