# Generated by Django 5.2.4 on 2026-03-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offboarding", "0004_rename_notify_at_offboardingtask_notified_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="offboardingtask",
            old_name="notified_completed",
            new_name="notified_need_payroll",
        ),
        migrations.AlterField(
            model_name="offboardingtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активна"),
                    ("completed", "Завершена"),
                    ("deleted", "Удалена"),
                    ("error", "Ошибка"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
