# Generated by Django 5.2.4 on 2026-03-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "offboarding",
            "0005_rename_notified_completed_offboardingtask_notified_need_payroll_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offboardingtask",
            name="is_complete",
        ),
    ]
