# Generated by Django 5.2.4 on 2025-11-03 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsanaProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("complete_section_id", models.CharField(max_length=100)),
                ("table_url", models.CharField(max_length=100, unique=True)),
                ("secret", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AsanaWebhookRequestData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("headers", models.JSONField()),
                ("payload", models.JSONField()),
                ("is_target_event", models.BooleanField(default=None, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vga_lands.asanaproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompletedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("event_data", models.JSONField()),
                ("task_id", models.CharField(max_length=100)),
                ("is_send_in_table", models.BooleanField(default=None, null=True)),
                ("response_text", models.TextField(blank=True)),
                ("error_text", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vga_lands.asanaproject",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vga_lands.asanawebhookrequestdata",
                    ),
                ),
            ],
        ),
    ]
