# Generated by Django 5.2.4 on 2026-01-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AtlasUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("role", models.CharField(max_length=64)),
                (
                    "tag",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("telegram", models.CharField(max_length=64)),
                ("username", models.CharField(max_length=64, unique=True)),
            ],
        ),
    ]
