# Generated by Django 5.2.4 on 2026-01-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atlasuser",
            name="telegram",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
