# Generated by Django 5.2.4 on 2026-01-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0002_alter_atlasuser_telegram"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("run_at", models.DateTimeField()),
                ("user_tag", models.CharField(blank=True, max_length=30)),
                (
                    "handler",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("domain_check", "DOMAIN_HANDLER"),
                            ("kva_test", "KVA_USER"),
                            ("asana_farm_comments", "FARM_GROUP"),
                            ("p1sms_balance", "SMS_SERVICE_BALANCE"),
                            ("offer_reawake", "OFFER_AWAKEN"),
                            ("onboarding", "ONBOARDING"),
                        ],
                        max_length=30,
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "run_at"],
                        name="message_sen_status_9ddfa9_idx",
                    )
                ],
            },
        ),
    ]
