# Generated by Django 5.2.4 on 2026-01-29 10:24

import message_sender.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0003_scheduledmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default=message_sender.models.ScheduledMessageStatus,
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("handler__isnull", True), ("user_tag__isnull", False)),
                    models.Q(("handler__isnull", False), ("user_tag__isnull", True)),
                    _connector="OR",
                ),
                name="only_one_of_user_tag_or_handler",
            ),
        ),
    ]
