# Generated by Django 5.2.4 on 2026-01-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0004_alter_scheduledmessage_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmessage",
            name="reference_id",
            field=models.CharField(
                blank=True,
                help_text="Logical connection to an object (e.g. leave-123) or other mark",
                max_length=100,
            ),
        ),
    ]
