# Generated by Django 5.2.4 on 2026-01-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0005_scheduledmessage_reference_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scheduledmessage",
            name="only_one_of_user_tag_or_handler",
        ),
        migrations.AlterField(
            model_name="scheduledmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("handler__gt", ""), ("user_tag", "")),
                    models.Q(("handler", ""), ("user_tag__gt", "")),
                    _connector="OR",
                ),
                name="only_one_of_user_tag_or_handler",
            ),
        ),
    ]
