# Generated by Django 5.2.4 on 2026-02-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "message_sender",
            "0006_remove_scheduledmessage_only_one_of_user_tag_or_handler_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledmessage",
            name="handler",
            field=models.CharField(
                blank=True,
                choices=[
                    ("domain_check", "DOMAIN_HANDLER"),
                    ("kva_test", "KVA_USER"),
                    ("asana_farm_comments", "FARM_GROUP"),
                    ("p1sms_balance", "SMS_SERVICE_BALANCE"),
                    ("offer_reawake", "OFFER_AWAKEN"),
                    ("onboarding", "ONBOARDING"),
                    ("hr_vacation", "HR_VACATION"),
                    ("luckstar_accounts", "LUCK_STAR_ACCOUNTS"),
                ],
                max_length=30,
            ),
        ),
    ]
