# Generated by Django 5.2.4 on 2026-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message_sender", "0007_alter_scheduledmessage_handler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledmessage",
            name="handler",
            field=models.CharField(
                blank=True,
                choices=[
                    ("domain_check", "DOMAIN_HANDLER"),
                    ("kva_test", "KVA_USER"),
                    ("asana_farm_comments", "FARM_GROUP"),
                    ("p1sms_balance", "SMS_SERVICE_BALANCE"),
                    ("offer_reawake", "OFFER_AWAKEN"),
                    ("onboarding", "ONBOARDING"),
                    ("hr_vacation", "HR_VACATION"),
                    ("luckstar_accounts", "LUCK_STAR_ACCOUNTS"),
                    ("kva_chat_test", "KVA_CHAT_TEST"),
                    ("HR__TECH_DEP", "HR__TECH_DEP"),
                    ("HR__DIZ_DEP", "HR__DIZ_DEP"),
                    ("HR__FARM_DEP", "HR__FARM_DEP"),
                    ("HR__BIZ_DEV", "HR__BIZ_DEV"),
                    ("HR__VGA_TEAM", "HR__VGA_TEAM"),
                ],
                max_length=30,
            ),
        ),
    ]
